id: 3fc0b5b5ea4541ef85e736a566c9c2f5
initial_creation_type: ocr
source_metadata:
  volumes:
    f094569e293d4ed1bdcecd7d4ab5fef8:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ''
      total_pages: 1853
      volume_number: 25
